### ISSUE TITLE
stops.json currently producing 500 error

### ISSUE THREAD

**Issue by alexelias** [joreilly/galway-bus-android#11]
Hi, thanks for making this sample app!  I've been starting to play around with it to learn Kotlin Multiplatform.  Today I noticed only the routes screen of the app is working (even the Play Store-downloaded version) -- the others are blank or they crash the app.

It looks like the underlying problem is that http://galwaybus.herokuapp.com/stops.json and http://galwaybus.herokuapp.com/stops/nearby.json are both returning internal server errors right now.

**Comment by joreilly** [comment]
@alexelias sorry, only noticed this now (haven't had much time to look at this project recently).  The issue you noticed was related to problem with back end service being used....which has just got resolved in last few days so should be working again.
